model_list:
  - model_name: genai/test/*
    litellm_params:
      model: openai/*
      api_base: https://api.openai.com
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  default_prompt_directory: /Users/krrishdholakia/Documents/litellm/litellm/proxy/test_prompts