model_list:
  - model_name: gpt-3.5-turbo-allow
    litellm_params:
      model: openai/gpt-3.5-turbo
    model_info: 
      version: 2
  - model_name: gpt-3.5-turbo-disallow
    litellm_params:
      model: openai/gpt-3.5-turbo
    model_info: 
      version: 2

router_settings:
  model_group_settings:
    forward_client_headers_to_llm_api: 
      - "gpt-3.5-turbo-allow"
