model_list:
  - model_name: "gemini/*"
    litellm_params:
      model: "gemini/*"
      api_key: os.environ/GEMINI_API_KEY
  - model_name: "[IP-approved] o3-pro"
    litellm_params:
      model: azure/responses/o_series/webinterface-o3-pro
      api_base: "https://webhook.site/fba79dae-220a-4bb7-9a3a-8caa49604e55"
      api_key: "sk-1234567890"
      api_version: "preview"
      stream: True
    model_info:
      input_cost_per_token: 0.00002     # $20 per 1M tokens
      output_cost_per_token: 0.00008    # $80 per 1M tokens