model_list:
  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*
  - model_name: openai/*
    litellm_params:
      model: openai/*



litellm_settings:
  callbacks: ["s3://litellm-proxy/custom_ui_sso_hook.custom_ui_sso_sign_in_handler"]