model_list:
  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_key: bad
  - model_name: openai/*
    litellm_params:
      model: openai/*


litellm_settings:
  callbacks: ["prometheus"]
  prometheus_metrics_config:
    - group: totals
      metrics:
        - litellm_spend_metric
        - litellm_total_tokens
        - litellm_input_tokens_metric
        - litellm_output_tokens_metric
      include_labels:
        - requested_modela
        - model