model_list:
  - model_name: openai/*
    litellm_params:
      model: openai/*
  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*
  - model_name: auto_router1
    litellm_params:
      model: auto_router/auto_router1
      auto_router_config_path: router.json
      auto_router_default_model: "gpt-4o"
      auto_router_embedding_model: "text-embedding-3-small"

litellm_settings:
  callbacks:
    - langfuse