model_list:
  - model_name: db-openai-endpoint
    litellm_params:
      model: openai/db-openai-endpoint
      base_url: https://db-openai-endpoint.us-east-1.amazonaws.com/v1
      mock_response: "Hi"


